# Generated by Django 4.2.5 on 2023-10-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                default="avatars/generico.jpg", upload_to="avatars"
            ),
        ),
    ]
