# Generated by Django 4.2.5 on 2023-10-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0002_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                default="Blog_Page/media/avatar/generico.png",
                upload_to="Blog_Page/media/avatar",
            ),
        ),
    ]
