# Generated by Django 4.2.5 on 2023-10-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0003_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(default="avatar/generico.png", upload_to="avatar/"),
        ),
    ]
