# Generated by Django 4.2.5 on 2023-10-15 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("AppBlog", "0002_blog_mensaje"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="contenido",
            new_name="cuerpo",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="resumen",
        ),
        migrations.AddField(
            model_name="blog",
            name="autor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="blogs/"),
        ),
        migrations.AddField(
            model_name="blog",
            name="subtitulo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
