# Generated by Django 4.2.5 on 2023-10-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppBlog", "0003_rename_contenido_blog_cuerpo_remove_blog_resumen_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resena",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="resena",
            name="pelicula",
        ),
        migrations.DeleteModel(
            name="Comentario",
        ),
        migrations.DeleteModel(
            name="Resena",
        ),
    ]
