# Generated by Django 4.2.5 on 2023-10-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppBlog", "0004_remove_resena_autor_remove_resena_pelicula_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mensaje",
        ),
    ]
